monolog:
  channels:
    - deprecation
    - project

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/main.log"
        level: debug
        channels: ["!event"]
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]
      project:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/project.log"
        level: info
        channels: [project]
        formatter: monolog.formatter.json

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/main.log"
        level: debug
      project:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%/project.log"
        level: info
        channels: [project]
        formatter: monolog.formatter.json

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
      nested:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%/main.log"
        level: debug
        max_files: 15
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      deprecation:
        type: rotating_file
        channels: [deprecation]
        path: "%kernel.logs_dir%/%kernel.environment%/deprecation.log"
        max_files: 15
        formatter: monolog.formatter.json
      project:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%/project.log"
        level: info
        channels: [project]
        max_files: 15
        formatter: monolog.formatter.json
