services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - "pgdata:/var/lib/postgresql"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_MAPPED_PORT}:${DATABASE_PORT}
    networks:
      - app

  php:
    build:
      context: ./php
      target: runtime
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/presentation-portfolio-project-api:cached
      - app_var:/var/www/presentation-portfolio-project-api/var
      - app_vendor:/var/www/presentation-portfolio-project-api/vendor
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      TEST_DATABASE_NAME: ${TEST_DATABASE_NAME}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app

  scheduler:
    build:
      context: ./php
      target: scheduler
      args:
        TIMEZONE: ${TIMEZONE}
    command: ["cron", "-f"]
    entrypoint: ["/usr/local/bin/scheduler-entrypoint.sh"]
    restart: unless-stopped
    volumes:
      - ../:/var/www/presentation-portfolio-project-api:cached
      - app_var:/var/www/presentation-portfolio-project-api/var
      - app_vendor:/var/www/presentation-portfolio-project-api/vendor
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgres
    networks:
      - app

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/presentation-portfolio-project-api:cached
      - app_var:/var/www/presentation-portfolio-project-api/var
      - app_vendor:/var/www/presentation-portfolio-project-api/vendor
    ports:
      - ${SERVER_MAPPED_PORT}:${SERVER_PORT}
    depends_on:
      - php
    networks:
      - app

volumes:
  app_var:
  app_vendor:
  pgdata:

networks:
  app:
