services:
  php:
    build:
      context: ..
      dockerfile: .docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    restart: unless-stopped
    env_file:
      - ../.env.prod
      - ../.env.prod.local
    networks:
      - backend
      - edge

networks:
  backend:
  edge:
    name: portfolio_edge
    external: true
